[package]
name = "bigus-gigus"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "*", features = ["rwh_05"] }
ahash = "*"
image = { version = "0.25" }
smallvec = "*"
ash = {version = "0.38", features = ["debug","loaded","linked","std"]}
tobj = {version = "4.0", features = ["log"]}

[profile.release]
debug = 1